language: 
  node_js
node_js:
  - "10.13.0"
cache:
  directories:
    - "node_modules"
env:
 global:
   - export NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run migrate:undo
  - npm run migrate
  - npm run seed
after_script:
  - after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage
