openapi: 3.0.1

info:
  title: Hello Books API
  description: |
    Hello-Books is a simple application that helps manage a library and its processes like stocking, tracking and renting books. With this application users are able to find and rent books.
  contact:
    email: team-hellobooks@domain.com
  license:
    name: MIT
    url: https://github.com/emp-daisy/HelloBooksLib/blob/develop/LICENSE
  version: 1.0.0

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/emp-daisy/HelloBooksLib

servers:
- url: /api/v1
- url: https://helobooks-staging.herokuapp.com/api/v1 # Heroku deployment (staging)

tags:
- name: User
  description: Operations available for user endpoints

paths:
  /oauth/google:
    post:
      tags:
        - Users
      summary : Gets the user details from their google accounts, and logs him in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                access_token:
                  type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Bad request
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/errorResponce"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string

    errorResponce:
      type: object
      properties:
        status:
          type: number
        error:
          type: string
